[package]
name = "rusty_blitzcrank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
serenity = { default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
#serenity = "0.11"
dotenv = "0.15.0"
rand = "0.8.5"