# This is a basic workflow that is manually triggered

name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
      branches:
      - '$default-branch'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull-and-build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Pull
      run: git pull origin master https://github.com/connorcinna/RustyBlitzcrank.git
    - name: Run
      run: systemctl restart blitzcrank.service
