name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
      branches:
        - master
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    runs-on: self-hosted
    environment: production
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Copy environment variables
       run: cat /home/connor/projects/RustyBlitzcrank/.env > .env

     - name: Build
       run: cargo build --release

     - name: Run
       run: RUNNER_TRACKING_ID="" && (nohup ./target/release/rusty_blitzcrank &)
